spring:
  datasource:
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false


swagger:
    show: true
    basepackage: com.chao.example.controller #扫描api包路径
    service:
        name: API #api名称
        description: api #api描述
        developer: machao #api开发

mybatis:
  type-aliases-package: com.chao.example.domain
  config-locations: classpath:mybatis/mybatis-config.xml
  mybatis.mapper-locations: classpath:com/chao/example/mapper/*.xml
